project:
  output-dir: ./_site/jp
  
website:
  site-url: https://blog.zarathu.com/jp
  repo-url: https://github.com/zarathucorp/blog
  description: "Zarathuからのニュース、洞察、詳細なケーススタディ"
  favicon: img/logo_favicon.png
  google-analytics: "UA-135478021-2"
  page-navigation: true
  page-footer:
    background: "#0F2E3D"
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2019. [Zarathu Co.,Ltd.](https://www.zarathu.com) All rights reserved.
      Licence: [MIT](https://opensource.org/license/mit-0/).
    border: true
  search:
    location: navbar
    type: overlay
  navbar:
    logo: img/logo.png
    right:
    - text: "ホーム"
      href: ../jp/index.html
    - text: "アプリケーション"
      href: https://openstat.ai/
      target: _blank
    - text: R パッケージ
      menu:
      - text: jstable      
        href: https://jinseob2kim.github.io/jstable/
        target: _blank
      - text: jskm
        href: https://jinseob2kim.github.io/jskm/
        target: _blank
      - text: jsmodule
        href: https://jinseob2kim.github.io/jsmodule/
        target: _blank
    - text: 投稿者
      href: ../jp/contributors.html
    - text: パートナー
      menu:
      - text: <img src='https://www.r-bloggers.com/favicon.ico'> R-bloggers
        href: https://www.r-bloggers.com/
        target: _blank
      - text: <img width = '16px' src='https://avatars.githubusercontent.com/u/46996346?s=200&v=4'> Shinykorea
        href: https://github.com/shinykorea/
        target: _blank
    - icon: github
      href: https://github.com/zarathucorp
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/company/zarathu/
      target: _blank
    - icon: rss
      href: index.xml
      aria-label: RSS
      target: _blank
    - icon: translate
      menu:
      - text: 한국어
        href: ../index.html
      - text: English
        href: ../en/index.html
      - text: 日本語
        href: ../jp/index.html