{
  "hash": "d6a4a4536df9d161d04141adf83970f4",
  "result": {
    "markdown": "---\ntitle: \"Process macro 소개\"\ndescription: 조절효과, 매개효과 분석을 위한 도구인 process macro를 소개합니다.\ncategories: [R]\nauthor: \n  name: Heeseok Choi\n  url: https://github.com/DilutionChoi\ndate: 03-14-2024\ndraft: false\n---\n\n\n# 개요\n\nProcess macro에 대해 알아보고 R에서 사용가능한 패키지를 소개합니다.\n\n# Process macro\n\nProcess macro는 회귀분석을 바탕으로 하는 매개효과, 조절효과 분석을 위한 도구입니다.\n\n사회과학, 경영학, 보건학 등에서 광범위하게 직접효과, 간접효과, 상호작용 등을 확인하기 위해 쓰입니다.\n\n## 매개효과\n\n\n\n\n\n매개효과 분석은 설명변수가 반응변수에 영향을 미치는 경로, 매커니즘을 확인하기 위한 분석방법입니다. 단순매개모형(4번 모델)은 다음과 같은 다이아그램으로 표현할 수 있습니다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure.1](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n먼저 R에서 process macro를 사용하려면 패키지를 설치하거나 파일을 다운받아야 합니다. 패키지로는 가톨릭대학교 문건웅 교수님이 만든 [processR](https://github.com/cardiomoon/processR)이라는 패키지를 다음과 같이 다운로드하고 불러올 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::install_github(\"cardiomoon/processR\")\nlibrary(processR)\n```\n:::\n\n\n`processR` 패키지를 사용하려면 `lavaan` 패키지가 필요합니다. 아래 코드로 다운로드하고 불러올 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"lavaan\")\nlibrary(lavaan)\n```\n:::\n\n\n아래 코드로 `processR` 패키지에서 지원하는 모델의 번호를 확인할 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npmacro$no\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  0.0  1.0  2.0  3.0  4.0  4.2  5.0  6.0  6.3  6.4  7.0  8.0  9.0 10.0 11.0\n[16] 12.0 13.0 14.0 15.0 16.0 17.0 18.0 19.0 20.0 21.0 22.0 23.0 24.0 28.0 29.0\n[31] 30.0 31.0 35.0 36.0 40.0 41.0 45.0 49.0 50.0 58.0 59.0 60.0 61.0 62.0 63.0\n[46] 64.0 65.0 66.0 67.0 74.0 75.0 76.0 25.0 26.0 27.0 58.2  4.3\n```\n:::\n:::\n\n\n직접 다운받아 사용하시려면 process macro를 개발한 Andrew F. Hayes가 제공하는 파일을 [여기](https://haskayne.ucalgary.ca/CCRAM/resource-hub)서 내려받을 수 있습니다. `process.R`파일을 실행시키거나 분석을 진행할 R파일 상단에 `source(\"process.R\")`코드를 실행하면 함수를 사용할 수 있습니다. `processR`패키지와 `process.R`파일은 서로 다른 도구이니 혼동하지 않도록 주의해야 합니다. 이 포스트에서 `processR` 패키지에서 제공하는 함수는 코드 상단에 `# processR`로, `process.R`에서 제공하는 함수는 `# process.R`로 주석을 달아놓겠습니다.\n\n\n\n\n\n예시 데이터로 단순매개효과를 설명해보겠습니다.\n\n미국의 1,338명의 의료비용에 대한 데이터입니다.\n\n::: {.cell}\n\n```{.r .cell-code}\ncost <- read.csv(\"Medical_Cost.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n| age|sex    |    bmi| children|smoker |region    |   charges|\n|---:|:------|------:|--------:|:------|:---------|---------:|\n|  19|female | 27.900|        0|yes    |southwest | 16884.924|\n|  18|male   | 33.770|        1|no     |southeast |  1725.552|\n|  28|male   | 33.000|        3|no     |southeast |  4449.462|\n|  33|male   | 22.705|        0|no     |northwest | 21984.471|\n|  32|male   | 28.880|        0|no     |northwest |  3866.855|\n:::\n:::\n\n\n`process.R`의 `process()`함수를 실행해보겠습니다. 인자는 다음과 같습니다.\n\n-   data = 데이터셋\n\n-   x = 설명변수\n\n-   y = 반응변수\n\n-   m = 매개변수\n\n-   model = 모델번호\n\n-   boot = 부트스트래핑 횟수\n\n-   total = 총효과 출력(0이면 출력하지 않음)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncost$sex <- ifelse(cost$sex == \"male\", 1, 0)\ncost$smoker <- ifelse(cost$smoker == \"yes\", 1, 0)\n\n# process.R\nprocess(data = cost, x = \"smoker\", y = \"charges\", m = \"bmi\", model = 4, boot = 0, total = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n********************* PROCESS for R Version 4.3.1 ********************* \n \n           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              \n   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   \n \n*********************************************************************** \n               \nModel : 4      \n    Y : charges\n    X : smoker \n    M : bmi    \n\nSample size: 1338\n\n\n*********************************************************************** \nOutcome Variable: bmi\n\nModel Summary: \n          R      R-sq       MSE         F       df1       df2         p\n     0.0038    0.0000   37.2152    0.0188    1.0000 1336.0000    0.8910\n\nModel: \n             coeff        se         t         p      LLCI      ULCI\nconstant   30.6518    0.1870  163.8953    0.0000   30.2849   31.0187\nsmoker      0.0567    0.4133    0.1371    0.8910   -0.7541    0.8674\n\n*********************************************************************** \nOutcome Variable: charges\n\nModel Summary: \n          R      R-sq           MSE         F       df1       df2         p\n     0.8111    0.6579 50238769.3992 1283.9234    2.0000 1335.0000    0.0000\n\nModel: \n              coeff        se         t         p       LLCI       ULCI\nconstant -3459.0955  998.2795   -3.4651    0.0005 -5417.4628 -1500.7282\nsmoker   23593.9810  480.1805   49.1357    0.0000 22651.9905 24535.9715\nbmi        388.0152   31.7875   12.2065    0.0000   325.6564   450.3741\n\n************************ TOTAL EFFECT MODEL *************************** \nOutcome Variable: charges\n\nModel Summary: \n          R      R-sq           MSE         F       df1       df2         p\n     0.7873    0.6198 55804130.1996 2177.6149    1.0000 1336.0000    0.0000\n\nModel: \n              coeff        se         t         p       LLCI       ULCI\nconstant  8434.2683  229.0142   36.8286    0.0000  7985.0017  8883.5348\nsmoker   23615.9635  506.0753   46.6649    0.0000 22623.1748 24608.7523\n\n************ TOTAL, DIRECT, AND INDIRECT EFFECTS OF X ON Y ************\n\nTotal effect of X on Y:\n      effect        se         t         p       LLCI       ULCI\n  23615.9635  506.0753   46.6649    0.0000 22623.1748 24608.7523\n\nDirect effect of X on Y:\n      effect        se         t         p       LLCI       ULCI\n  23593.9810  480.1805   49.1357    0.0000 22651.9905 24535.9715\n\nIndirect effect(s) of X on Y:\n       Effect\nbmi   21.9825\n\n******************** ANALYSIS NOTES AND ERRORS ************************ \n\nLevel of confidence for all confidence intervals in output: 95\n```\n:::\n:::\n\n\n우선 Figure.1에서 보았던 경로의 이름을 정하겠습니다.<br> $X → M : a$<br> $M → Y : b$<br> $X → Y : c'$<br> 단순매개모형에서 설명변수가 0, 1로 이루어진 변수일때, $a = [\\bar{M}|(X = 1)] - [\\bar{M}|(X = 0)] = 0.0567$이며 X가 1일때 M의 평균과 X가 0일때 M의 평균의 차이와 같고 `lm(bmi ~ smoker, data = cost)`의 기울기와 같습니다.<br> $b = [\\hat{Y}|(M = m, X = x)] - [\\hat{Y}|(M = m - 1, X = x)] = 388.0152$이며 이는 `lm(charges ~ smoker + bmi, data = cost)`에서 bmi의 기울기와 같고 아래처럼 계산할 수도 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(charges ~ bmi + smoker, data = cost)\n\ncost.1 <- cost\ncost.1$bmi <- cost.1$bmi - 1\n\npredict(model, cost)[1] - predict(model, cost.1)[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n388.0152 \n```\n:::\n:::\n\n\n$c' = [\\hat{Y}|(X = x, M = m)] - [\\hat{Y}|(X = x - 1, M = m)] = 23593.9810$이며 `lm(charges ~ smoker + bmi, data = cost)`의 smoker의 기울기와 같고 다음과 같이 계산할 수도 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(charges ~ bmi + smoker, data = cost)\n\nsmoke1 <- cost\nsmoke1$smoker <- 1\n\nsmoke0 <- cost\nsmoke0$smoker <- 0\n\npredict(model, smoke1)[1] - predict(model, smoke0)[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n23593.98 \n```\n:::\n:::\n\n\n단순매개모형에서 $ab$를 간접효과, $c'$을 직접효과, 이 둘을 더한 값을 $c$(총효과)라고 하며 총효과는 `lm(charges ~ smoker, data = cost)`의 기울기와 같습니다.<br> 간접효과는 매개변수를 통했을 때 흡연자는 비흡연자보다 의료비용이 21.9825만큼 높다는 것을 의미하며, 직접효과는 매개변수가 고정되어있을 때 흡연자는 의료비용이 23593.981만큼 더 높다는 것을 의미합니다.<br> 이제 `processR` 패키지를 실행해보겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# processR\nlabels <- list(X = \"smoker\", Y = \"charges\", M = \"bmi\")\nmeanSummaryTable(labels = labels, data = cost)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-b97c7df0{}.cl-b973a036{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b973a040{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9778188{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9778192{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9779baa{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(237, 189, 62, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bb4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(237, 189, 62, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bb5{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(237, 189, 62, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bbe{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(237, 189, 62, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bbf{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bc8{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bc9{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bca{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bd2{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9779bd3{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b97c7df0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9779baa\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\"></span></p></th><th class=\"cl-b9779bb4\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\"> </span></p></th><th class=\"cl-b9779bb4\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">Y</span></p></th><th class=\"cl-b9779bb4\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">M</span></p></th><th class=\"cl-b9779bb4\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">Y</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9779bb5\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\"></span></p></th><th class=\"cl-b9779bbe\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\"></span></p></th><th class=\"cl-b9779bbe\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">charges</span></p></th><th class=\"cl-b9779bbe\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">bmi</span></p></th><th class=\"cl-b9779bbe\"><p class=\"cl-b9778188\"><span class=\"cl-b973a036\">adjusted</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bbf\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">smoker(X) = 0</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">Mean</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">8434.268</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">30.652</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">8438.77</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bbf\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">SD</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">5993.782</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">6.043</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bbf\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">smoker(X) = 1</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">Mean</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">32050.232</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">30.708</span></p></td><td class=\"cl-b9779bc8\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">32032.751</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bbf\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td><td class=\"cl-b9779bc9\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">SD</span></p></td><td class=\"cl-b9779bc9\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">11541.547</span></p></td><td class=\"cl-b9779bc9\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">6.319</span></p></td><td class=\"cl-b9779bc9\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bbf\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td><td class=\"cl-b9779bca\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">Mean</span></p></td><td class=\"cl-b9779bca\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">13270.422</span></p></td><td class=\"cl-b9779bca\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">30.663</span></p></td><td class=\"cl-b9779bca\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9779bd2\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td><td class=\"cl-b9779bd3\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">SD</span></p></td><td class=\"cl-b9779bd3\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">12110.011</span></p></td><td class=\"cl-b9779bd3\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\">6.098</span></p></td><td class=\"cl-b9779bd3\"><p class=\"cl-b9778192\"><span class=\"cl-b973a040\"></span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nAdjusted mean은 $adjusted\\;mean(\\bar{Y}^*) = i_{Y} + b\\bar{M} + c'X$로 계산할 수 있습니다. 설명변수가 0일때는 $\\bar{Y}^* = -3459.10 + 388.02 * 30.6634 + 23593.98 * 0$이고 설명변수가 1일때는 $\\bar{Y}^* = -3459.10 + 388.02 * 30.6634 + 23593.98 * 1$로 계산할 수 있습니다. 보정평균은 $X$일때 평균적인 $M$의 값을 가지는 사람은 보정평균만큼의 $Y$를 갖는다는 것을 의미합니다.\n\n아래처럼 각 계수를 깔끔하게 출력하는 함수도 존재합니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# processR\nmodelsSummaryTable(labels = labels, data = cost)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-b9b76618{}.cl-b9aea3b6{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9aea3c0{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9aea3c1{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9aea3c2{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9aea3ca{font-family:'DejaVu Sans';font-size:7.2pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-b9b23800{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9b2380a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9b25006{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25010{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2501a{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2501b{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2501c{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(255, 255, 255, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25024{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25025{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25026{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2502e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2502f{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(255, 255, 255, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25038{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25039{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2503a{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25042{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25043{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25044{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2504c{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2504d{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2504e{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25056{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25057{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25058{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25060{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25061{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25062{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2506a{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2506b{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2506c{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25074{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b25075{width:0.001in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9b2507e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b9b76618'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9b25006\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th  colspan=\"11\"class=\"cl-b9b25010\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">Consequent</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9b2501c\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th  colspan=\"4\"class=\"cl-b9b25025\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">bmi(M)</span></p></th><th class=\"cl-b9b25026\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th  colspan=\"4\"class=\"cl-b9b2502e\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">charges(Y)</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9b2501c\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">Antecedent</span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">Coef</span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">SE</span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">t</span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">p</span></p></th><th class=\"cl-b9b2502f\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th class=\"cl-b9b25024\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\"></span></p></th><th class=\"cl-b9b25038\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">Coef</span></p></th><th class=\"cl-b9b25038\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">SE</span></p></th><th class=\"cl-b9b25038\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c0\">t</span></p></th><th class=\"cl-b9b25038\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3b6\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25039\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">smoker(X)</span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\">a</span><span class=\"cl-b9aea3ca\"></span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">0.057</span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">0.413</span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">0.137</span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">.891</span></p></td><td class=\"cl-b9b25043\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\">c'</span><span class=\"cl-b9aea3ca\"></span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">23593.981</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">480.180</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">49.136</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">&lt;.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25039\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">bmi(M)</span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25042\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25043\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\">b</span><span class=\"cl-b9aea3ca\"></span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">388.015</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">31.787</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">12.207</span></p></td><td class=\"cl-b9b25044\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">&lt;.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b2504c\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">Constant</span></p></td><td class=\"cl-b9b2504d\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\">i</span><span class=\"cl-b9aea3ca\">M</span></p></td><td class=\"cl-b9b2504e\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">30.652</span></p></td><td class=\"cl-b9b2504e\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">0.187</span></p></td><td class=\"cl-b9b2504e\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">163.895</span></p></td><td class=\"cl-b9b2504e\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">&lt;.001</span></p></td><td class=\"cl-b9b25056\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2504d\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\">i</span><span class=\"cl-b9aea3ca\">Y</span></p></td><td class=\"cl-b9b25057\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">-3459.096</span></p></td><td class=\"cl-b9b25057\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">998.279</span></p></td><td class=\"cl-b9b25057\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">-3.465</span></p></td><td class=\"cl-b9b25057\"><p class=\"cl-b9b2380a\"><span class=\"cl-b9aea3c1\">.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25058\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">Observations</span></p></td><td class=\"cl-b9b25060\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b25060\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">1338</span></p></td><td class=\"cl-b9b25061\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25060\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b25062\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">1338</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25039\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">R2</span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">0.000</span></p></td><td class=\"cl-b9b2506a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2506b\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">0.658</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25039\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">Adjusted R2</span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">-0.001</span></p></td><td class=\"cl-b9b2506a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2506b\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">0.657</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b25039\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">Residual SE</span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">6.100 ( df = 1336)</span></p></td><td class=\"cl-b9b2506a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b2503a\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2506b\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">7087.931 ( df = 1335)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9b2506c\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">F statistic</span></p></td><td class=\"cl-b9b25074\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b25074\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">F(1,1336) = 0.019, p = .891</span></p></td><td class=\"cl-b9b25075\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\"></span></p></td><td class=\"cl-b9b25074\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c2\"></span><span class=\"cl-b9aea3ca\"></span></p></td><td  colspan=\"4\"class=\"cl-b9b2507e\"><p class=\"cl-b9b23800\"><span class=\"cl-b9aea3c1\">F(2,1335) = 1283.923, p &lt; .001</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n간접효과, 직접효과, 총효과를 다음 함수로 출력할 수 있습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# processR\nmodel <- tripleEquation(labels = labels)\nsemfit <- sem(model = model, data = cost)\n\nmedSummaryTable(semfit)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-b9f1936a{}.cl-b9ea1284{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9ea128e{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b9ed582c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9ed5836{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b9ed6dda{width:1.513in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6de4{width:1.537in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6de5{width:1.186in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6de6{width:2.491in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6dee{width:1.513in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6def{width:1.537in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6df8{width:1.186in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e02{width:2.491in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e03{width:1.513in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e04{width:1.537in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e0c{width:1.186in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e0d{width:2.491in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e16{width:1.513in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e17{width:1.537in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e20{width:1.186in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b9ed6e21{width:2.491in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b9f1936a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b9ed6dda\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea1284\">Effect</span></p></th><th class=\"cl-b9ed6de4\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea1284\">Equation</span></p></th><th class=\"cl-b9ed6de5\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea1284\">estimate</span></p></th><th class=\"cl-b9ed6de6\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea1284\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9ed6dee\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">indirect</span></p></td><td class=\"cl-b9ed6def\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">(a)*(b)</span></p></td><td class=\"cl-b9ed6df8\"><p class=\"cl-b9ed5836\"><span class=\"cl-b9ea128e\">21.983</span></p></td><td class=\"cl-b9ed6e02\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">(-292.098 to 336.063)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9ed6e03\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">direct</span></p></td><td class=\"cl-b9ed6e04\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">c</span></p></td><td class=\"cl-b9ed6e0c\"><p class=\"cl-b9ed5836\"><span class=\"cl-b9ea128e\">23593.981</span></p></td><td class=\"cl-b9ed6e0d\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">(22653.900 to 24534.062)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9ed6e03\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">total</span></p></td><td class=\"cl-b9ed6e04\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">direct+indirect</span></p></td><td class=\"cl-b9ed6e0c\"><p class=\"cl-b9ed5836\"><span class=\"cl-b9ea128e\">23615.964</span></p></td><td class=\"cl-b9ed6e0d\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">(22624.816 to 24607.111)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b9ed6e16\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">prop.mediated</span></p></td><td class=\"cl-b9ed6e17\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">indirect/total</span></p></td><td class=\"cl-b9ed6e20\"><p class=\"cl-b9ed5836\"><span class=\"cl-b9ea128e\">0.001</span></p></td><td class=\"cl-b9ed6e21\"><p class=\"cl-b9ed582c\"><span class=\"cl-b9ea128e\">(-0.012 to 0.014)</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n## 조절효과\n\n조절효과는 설명변수가 반응변수에 미치는 영향이 다른 변수에 의해 변화될 때, 이 변화를 조절효과라고 하며, 이러한 영향을 주는 변수를 조절변수라고 합니다.\n\n단순조절효과(1번모델)는 다음의 다이아그램으로 나타낼 수 있습니다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure.2](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n`process()`함수로 단순조절효과를 알아보겠습니다. `plot` 인자는 출력결과 하단에 테이블을 만드어줍니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# process.R\nprocess(data = cost, x = \"smoker\", y = \"charges\", w = \"age\", model = 1, plot = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n********************* PROCESS for R Version 4.3.1 ********************* \n \n           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              \n   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   \n \n*********************************************************************** \n               \nModel : 1      \n    Y : charges\n    X : smoker \n    W : age    \n\nSample size: 1338\n\n\n*********************************************************************** \nOutcome Variable: charges\n\nModel Summary: \n          R      R-sq           MSE         F       df1       df2         p\n     0.8495    0.7217 40903347.7298 1153.1995    3.0000 1334.0000    0.0000\n\nModel: \n              coeff        se         t         p       LLCI       ULCI\nconstant -2091.4206  582.5654   -3.5900    0.0003 -3234.2647  -948.5764\nsmoker   22385.5487 1278.7311   17.5061    0.0000 19877.0057 24894.0917\nage        267.2489   13.9285   19.1872    0.0000   239.9247   294.5731\nInt_1       37.9887   31.0950    1.2217    0.2220   -23.0116    98.9890\n\nProduct terms key:\nInt_1  :  smoker  x  age      \n\nTest(s) of highest order unconditional interaction(s):\n      R2-chng         F       df1       df2         p\nX*W    0.0003    1.4925    1.0000 1334.0000    0.2220\n----------\nFocal predictor: smoker (X)\n      Moderator: age (W)\n\nData for visualizing the conditional effect of the focal predictor:\n     smoker       age    charges\n     0.0000   22.0000  3788.0555\n     1.0000   22.0000 27009.3554\n     0.0000   39.0000  8331.2870\n     1.0000   39.0000 32198.3946\n     0.0000   56.0000 12874.5186\n     1.0000   56.0000 37387.4338\n\n******************** ANALYSIS NOTES AND ERRORS ************************ \n\nLevel of confidence for all confidence intervals in output: 95\n```\n:::\n:::\n\n\n단순조절효과의 계수는 `lm(charges ~ smoker + age + smoker * charges, data = cost)`의 계수와 동일합니다.\n\n$\\hat{Y} = i_{Y} + b_{1}X + b_{2}W + b_{3}XW$일때, $b_{1} = 23385.55$, $b_{2} = 267.25$, $b_{3} = 37.99$이며 각 계수를 다음과 같은 의미를 가지고 있습니다.\n\n-   $b_{1} = W$가 $0$일때 $X$가 $Y$에 미치는 조건부 효과이고 $X$가 $Y$에 미치는 조건부 효과는 $\\theta_{X→Y} = b_{1} + b_{3}W$로 계산합니다.\n\n-   $b_{2} = X$가 $0$일때 $W$가 $Y$에 미치는 조건부 효과이고 $W$가 $Y$에 미치는 조건부 효과는 $\\theta_{W→Y} = b_{2} + b_{3}X$로 계산합니다.\n\n-   $b_{3} = W$가 한 단위 바뀔 때, $X$의 한 단위 변화가 $Y$에 영향을 미치는 정도의 차이입니다.\n\n`proceeR` 패키지로 확인해보겠습니다.\n\n::: {.cell}\n\n```{.r .cell-code}\nlabels <- list(X = \"smoker\", Y = \"charges\", W = \"age\")\nmodel <- lm(charges ~ smoker + age + smoker * age, data = cost)\n\n# processR\nm.summary <- modelsSummary(list(model), labels = labels)\nmodelsSummaryTable(m.summary)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-ba64d0a0{}.cl-ba5c94b2{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ba5c94bc{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ba5c94bd{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ba5c94c6{font-family:'DejaVu Sans';font-size:7.2pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-ba601b96{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ba601ba0{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ba603270{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603271{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba60327a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 2pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba60327b{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(255, 255, 255, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603284{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603285{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603286{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba60328e{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba60328f{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603290{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603298{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba603299{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032a2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(190, 190, 190, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032a3{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032ac{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032ad{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(190, 190, 190, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032ae{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032b6{width:0.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032b7{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ba6032b8{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-ba64d0a0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ba603270\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\"></span></p></th><th  colspan=\"5\"class=\"cl-ba603271\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">Consequent</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ba60327b\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\"></span></p></th><th class=\"cl-ba603284\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\"></span></p></th><th  colspan=\"4\"class=\"cl-ba603285\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">charges(Y)</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-ba60327b\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">Antecedent</span></p></th><th class=\"cl-ba603284\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\"></span></p></th><th class=\"cl-ba603286\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">Coef</span></p></th><th class=\"cl-ba603286\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">SE</span></p></th><th class=\"cl-ba603286\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">t</span></p></th><th class=\"cl-ba603286\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94b2\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">smoker(X)</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\">c</span><span class=\"cl-ba5c94c6\">1</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">22385.549</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">1278.731</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">17.506</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">&lt;.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">age(W)</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\">c</span><span class=\"cl-ba5c94c6\">2</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">267.249</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">13.929</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">19.187</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">&lt;.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">smoker:age(X:W)</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\">c</span><span class=\"cl-ba5c94c6\">3</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">37.989</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">31.095</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">1.222</span></p></td><td class=\"cl-ba603290\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">.222</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba603298\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">Constant</span></p></td><td class=\"cl-ba603299\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\">i</span><span class=\"cl-ba5c94c6\">Y</span></p></td><td class=\"cl-ba6032a2\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">-2091.421</span></p></td><td class=\"cl-ba6032a2\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">582.565</span></p></td><td class=\"cl-ba6032a2\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">-3.590</span></p></td><td class=\"cl-ba6032a2\"><p class=\"cl-ba601ba0\"><span class=\"cl-ba5c94bc\">&lt;.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba6032a3\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">Observations</span></p></td><td class=\"cl-ba6032ac\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\"></span><span class=\"cl-ba5c94c6\"></span></p></td><td  colspan=\"4\"class=\"cl-ba6032ad\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">1338</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">R2</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\"></span><span class=\"cl-ba5c94c6\"></span></p></td><td  colspan=\"4\"class=\"cl-ba6032ae\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">0.722</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">Adjusted R2</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\"></span><span class=\"cl-ba5c94c6\"></span></p></td><td  colspan=\"4\"class=\"cl-ba6032ae\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">0.721</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba60328e\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">Residual SE</span></p></td><td class=\"cl-ba60328f\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\"></span><span class=\"cl-ba5c94c6\"></span></p></td><td  colspan=\"4\"class=\"cl-ba6032ae\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">6395.573 ( df = 1334)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-ba6032b6\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">F statistic</span></p></td><td class=\"cl-ba6032b7\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bd\"></span><span class=\"cl-ba5c94c6\"></span></p></td><td  colspan=\"4\"class=\"cl-ba6032b8\"><p class=\"cl-ba601b96\"><span class=\"cl-ba5c94bc\">F(3,1334) = 1153.199, p &lt; .001</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n# 마치며\n\n이 포스트에서는 간단한 모델만을 다뤘기 때문에 사용하지 못한 함수나 개념이 많습니다.\n\n추후에 기회가 된다면 포스트를 수정보완하여 좀 더 복잡한 모델을 소개할 수 있기를 바랍니다.\n\nProcess macro에 대해 좀 더 알고 싶으신 분들은 문재성 교수님의 [processRWorkshop](https://github.com/cardiomoon/processRWorkshop) 또는 Andrew F. Hayes의 \"Introduction to Mediation, Moderation, and Conditional Process Analysis\"를 참고하시면 도움이 될 수 있습니다.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}