{
  "hash": "c7f135f1939e8fe61b1f408f9a5ee40e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"의학 연구에서의 기술 통계 with R\"\ndescription: |\n  중앙보훈병원 정신건강의학과에서 강의한 내용으로, 의학 연구에 필요한 기술 통계(descriptive statistics)를 정리하고 웹 애플리케이션과 Rstudio Addins을 이용하여 실습하였습니다. \nimage: https://www.jobaba.net/file/image.do?filePath=YhbLfTRb2RBaWmlnWg8493cm8rlHOSSeIQqGBWfJDxflkdgRc6ia3PT2tEO92Cj9\ncategories:\n  - lecture\n  - statistics\n  - R\n  - shiny\nauthor:\n  - name: Jinseob Kim\n    url: https://github.com/jinseob2kim\n    affiliation: Zarathu Co.,Ltd\n    affiliation_url: https://www.zarathu.com\ndate: 11-28-2018\noutput:\n  distill::distill_article:\n    self_contained: false\n    toc: true\n    toc_depth: 2\nbibliography: ref.bib\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n[김진섭](https://github.com/jinseob2kim) 대표는 11월 28일(수) [중앙보훈병원 정신건강의학과](https://seoul.bohun.or.kr/040part/01_body.php?left=26&idx=82)를 방문, 의학 연구에 필요한 기술 통계(descriptive statistics)에 대해 강의하고 자체 제작한 [웹 애플리케이션](https://jinseob2kim.shinyapps.io/BasicStat/)과 [**Rstudio Addins**](https://rstudio.github.io/rstudioaddins/)를 이용하여 실습을 진행하였습니다. 강의 내용을 공유합니다.\n\n## 시작하기 전에\n\n의학연구에서 [**R**](https://www.r-project.org/) 활용 능력을 대략 5단계로 구분할 수 있다.\n\n1.  데이터 정리는 미리 excel로 완료, 통계분석만 [**R**](https://www.r-project.org/) 이용.\n\n2.  [**R**](https://www.r-project.org/)로 데이터 정리와 통계분석을 모두 수행.\n\n3.  [**R**](https://www.r-project.org/)로 그림을 그린다.\n\n4.  논문에 들어갈 Table과 figure를 모두 [**R**](https://www.r-project.org/)로 만든다.\n\n5.  글쓰기, 참고문헌 등 논문의 모든 작업을 [**R**](https://www.r-project.org/)에서 직접 수행한다.\n\n본 강의는 1단계에 해당하는 연구자가 [**R**](https://www.r-project.org/)을 쉽게 이용할 수 있도록 돕는 내용에 해당하며 [**R**](https://www.r-project.org/)과 [**Rstudio**](https://www.rstudio.com/)의 설치과정은 생략한다. 혹시 설치를 못했다면 <https://www.r-project.org> 와 [https://www.rstudio.com/products/rstudio/download](https://www.r-project.org%20와%20https://www.rstudio.com/products/rstudio/download) 를 참조하여 설치하길 바란다. [**R**](https://www.r-project.org/)의 전반적인 도움말은 `help.start()` 명령어를 활용하고 특정 함수를 보려면 `help(which)` 형태로 실행하면 된다.\n\n## 의학 연구에서의 기술 통계\n\n기술 통계는 원래 평균(mean), 중위수(median), 분산(variance), 빈도표(frequency table)등의 데이터를 설명하는 **숫자**들이나 히스토그램(histogram), 상자그림(box-plot)같은 **그래프**를 의미한다. 그러나 대부분의 의학 연구에서는 단순한 기술 통계가 아닌 그것들의 **그룹 비교**(ex: 성별, 질환 유무)가 Table 1에 기술 통계란 제목으로 제시된다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Table 1 example[@Balaji2011]](table1.jpg){width=244}\n:::\n:::\n\n\n보통 연구의 흐름은 **기술 통계**로 데이터를 보여주고 **단변량(univariate) 분석**을 통해 가설 검정을 수행한 후, **다변량(multivariate)** 혹은 **소그룹(subgroup) 분석** 을 이용하여 다른 변수들의 효과를 보정한 결과를 보여주는 것으로 이루어진다. 그러나 단변량 분석에서 끝나는 간단한 연구도 많고 이것은 본질적으로 기술 통계의 그룹 비교와 같으므로, Table 1에 필요한 통계를 알고 쉽게 구현할 수 있다면 그것만으로 간단한 의학 연구를 수행할 수 있다.\n\n본 강의에서는 Table 1의 그룹 비교에 필요한 통계 방법들을 알아보고 [**R**](https://www.r-project.org/)을 이용해서 실제 분석을 수행할 것이다. 통계 방법을 선택하는 기준은 크게 **(1) 연속 변수(continuous variable) vs 범주형 변수(categorical variable)**, **(2) 비교할 그룹 수**, **(3) 샘플 수 혹은 정규분포 여부** 의 3가지가 있으며 추가로 짝지은 그룹인 경우를 살펴보겠다.\n\n마지막으로 자체 개발한 [웹 애플리케이션](https://jinseob2kim.shinyapps.io/BasicStat/)과 [**Rstudio Addins**](https://rstudio.github.io/rstudioaddins/)을 사용하여 간단히 Table 1을 만들어 볼 것이다(Figure \\@ref(fig:appgif), \\@ref(fig:addingif)).\n\n## 연속 변수의 그룹 비교\n\n연속 변수의 그룹 비교는 2 그룹일 때는 **t-test**, 3 그룹 이상이면 **ANOVA**라고 생각하면 되며, 2 그룹일 때 **ANOVA** 결과는 **t-test** 결과와 **거의(?)** 같다. 따라서 연속 변수는 무조건 **ANOVA**라고 생각해도 대충 맞다.\n\n### **T-test**\n\n**T-test**는 2 그룹의 **평균값**을 비교하는 통계 방법[^1]으로 필요한 숫자는 각 그룹의 **평균과 분산**이다. 실제로 데이터 없이 두 그룹의 평균과 분산만 있어도 **t-test**를 수행할 수 있으며 <https://www.evanmiller.org/ab-testing/t-test.html> 를 통해 웹에서도 간단히 계산할 수 있다. 아래 남녀의 총 콜레스테롤 데이터를 이용해 **t-test**를 수행해 보자.\n\n[^1]: 1 그룹의 평균값을 특정 숫자와 비교할 수도 있다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-4b5ea45ccdc1f9093593\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-4b5ea45ccdc1f9093593\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.t: sex and total cholesterol<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\"],[\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Female\"],[137,133,169,142,153,130,151,153,192,116,156,196,122,145,148,179,143,143,156,206,159,169,144,164,177,190,205,146,137,170]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>sex<\\/th>\\n      <th>tChol<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"sex\",\"targets\":1},{\"name\":\"tChol\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n이제 `t.test` 함수를 이용하여 남녀의 총 콜레스테롤 수치를 비교한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnev.ttest <- t.test(tChol ~ sex, data = data.t, var.equal = F)\nnev.ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  tChol by sex\nt = 0.35081, df = 19.752, p-value = 0.7294\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n -15.59551  21.89551\nsample estimates:\nmean in group Female   mean in group Male \n              158.75               155.60 \n```\n\n\n:::\n:::\n\n\n여자의 평균 콜레스테롤 값은 158.8, 남자는 155.6 이고 $p$-value는 0.729임을 확인할 수 있다.\n\n위의 `t.test` 함수의 옵션 중 `var.equal = F`는 등분산 가정 없이 분석하겠다는 뜻으로 옵션을 적지 않아도 기본적으로 `F`가 적용된다. 등분산 가정이란 두 그룹의 분산이 같다고 가정하는 것인데, 계산이 좀 더 쉽다는 이점이 있으나 아무 근거 없이 분산이 같다고 가정하는 것은 위험한 가정이다. 위의 분석에 `var.equal = T`를 적용해보자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev.ttest <- t.test(tChol ~ sex, data = data.t, var.equal = T)\nev.ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  tChol by sex\nt = 0.33954, df = 28, p-value = 0.7367\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n -15.85373  22.15373\nsample estimates:\nmean in group Female   mean in group Male \n              158.75               155.60 \n```\n\n\n:::\n:::\n\n\n앞서는 Welch t-test였는데 이름이 바뀐 것을 확인할 수 있고 $p$-value도 0.737로 아까와 다르다. 논문 리뷰어가 요구하는 등의 특별한 경우가 아니고서야 위험한 등분산가정을 할 필요가 없고, 이제부터 `var.equal` 옵션은 신경쓰지 않아도 좋다.\n\n### **ANOVA**[^2]\n\n[^2]: 본 강의에서는 One-way ANOVA만 다룬다.\n\n3 그룹 이상일 때는 2그룹씩 짝을 지어서 **t-test**를 여러 번 수행할 수 있다. 그러나 Table 1에서는 대부분 하나의 $p$-value만 제시하고 이것은 전체적으로 **튀는 것이 하나라도 있는가?**를 테스트하는 **ANOVA**를 이용한다.[^3] **ANOVA**는 비교할 모든 그룹에서 분산이 같다는 등분산 가정 하에 분석을 수행하며, 실제로 2 그룹일 때 **ANOVA**를 수행하면 등분산 가정 하에 수행한 **t-test**와 동일한 결과를 얻는다. 위에도 언급했듯이 모든 그룹에서 분산이 같다는 것은 너무 위험한 가정이나, 3 그룹 이상인 경우 마땅한 대안이 없고 Table 1에서 엄밀한 통계를 요구하는 것도 아니기 때문에 그냥 **ANOVA**를 쓰는 것이 관행이다. 아래 세 그룹의 총 콜레스테롤 데이터를 활용해 분석을 수행해 보자.\n\n[^3]: 사후(post-hoc) 분석을 이용, 어떤 것이 튀는지를 알아볼 수도 있다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-b8445bf5edadb486fd9d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b8445bf5edadb486fd9d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.t: group and total cholesterol<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\"],[\"C\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"A\",\"A\",\"B\",\"B\",\"B\",\"A\",\"C\",\"B\",\"B\",\"A\",\"B\",\"A\",\"A\",\"A\",\"C\",\"C\",\"B\",\"A\",\"B\",\"A\",\"B\",\"B\"],[157,148,193,159,96,172,143,147,166,106,153,146,138,191,190,151,189,151,100,120,127,109,142,204,220,102,190,148,152,98]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>group<\\/th>\\n      <th>tChol<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"group\",\"targets\":1},{\"name\":\"tChol\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n이제 `aov`함수를 이용하여 3 그룹의 평균 콜레스테롤 값을 한번에 비교한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.aov <- aov(tChol ~ group, data = data.aov)\nsummary(res.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\ngroup        2   2881    1441   1.304  0.288\nResiduals   27  29829    1105               \n```\n\n\n:::\n:::\n\n\n결과에서 나온 $p$-value인 0.288가 Table 1에 이용되며 의미는 \"**3 그룹에서 총콜레스테롤 값이 비슷하다**(다른 것이 있다고 할 수 없다)\" 이다.\n\n### 비모수 통계: 정규분포 아닐 때\n\n**T-test**나 **ANOVA**는 모두 변수가 정규분포를 이룬다고 가정하고 분석을 수행하는데, 언뜻 생각하기에 의학에서 정규분포가 아닌 변수는 없을 것 같지만[^4] 일부 지표(ex: CRP, 자녀 수)들은 정규분포를 따르지 않는다고 알려져 있다. 이 때는 변수의 값 자체가 아닌 순위 정보만을 이용하는 비모수 검정을 이용한다. **T-test**에 대응되는 비모수 분석은 **Wilcoxon rank-sum test** 혹은 **Mann--Whitney U test** 로 불리며 앞서 이용한 남녀별 총 콜레스테롤 데이터로 분석을 수행하면 아래와 같다.\n\n[^4]: 정규분포에 대한 내용은 [https://jinseob2kim.github.io/Normal_distribution.html](https://jinseob2kim.github.io/Normal_distribution.html) 를 참고하기 바란다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.wilcox <- wilcox.test(tChol ~ sex, data = data.t)\nres.wilcox\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  tChol by sex\nW = 104.5, p-value = 0.8602\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n위 결과에서 $p$-value는 0.86임을 확인할 수 있다. **ANOVA**에 대응되는 비모수 분석은 **Kruskal--Wallis one-way ANOVA**이며 역시 앞서 이용한 그룹별 총 콜레스테롤 데이터에 적용하면 아래와 같다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.kruskal <- kruskal.test(tChol ~ group, data = data.aov)\nres.kruskal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  tChol by group\nKruskal-Wallis chi-squared = 2.0319, df = 2, p-value = 0.3621\n```\n\n\n:::\n:::\n\n\n마찬가지로 $p$-value는 0.362임을 확인할 수 있다.\n\n## 범주형 변수의 그룹 비교\n\n범주형 변수의 그룹 비교는 그룹 수나 정규분포를 고려할 필요가 없어 연속 변수일 때보다 훨씬 간단하며 딱 하나, 샘플 수가 충분한지만 확인하면 된다.\n\n### 샘플 수 충분: Chi-square test\n\n**Chi-square test**는 두 범주형 변수가 관계가 있는지 없는지를 파악하는 테스트로[^5] 아래의 혈압약과 당뇨약 복용 여부를 조사한 데이터로 분석을 수행해 보겠다.\n\n[^5]: 세 범주형 변수일 때도 이용할 수 있으나 본 강의에서는 생략한다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-1fe3b7c4b550c7a86063\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1fe3b7c4b550c7a86063\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.chi: HTN &amp; DM medication<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\",\"person 31\",\"person 32\",\"person 33\",\"person 34\",\"person 35\",\"person 36\",\"person 37\",\"person 38\",\"person 39\",\"person 40\",\"person 41\",\"person 42\",\"person 43\",\"person 44\",\"person 45\",\"person 46\",\"person 47\",\"person 48\",\"person 49\",\"person 50\"],[1,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,1,1,0,0,1,0,1,0,0,0,1,1,0,0,1,1,1,1,1,0,1,1,1,0,1],[0,0,1,1,0,0,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,1,0,0,1,1,1,1,0,1,1,0,0,1,0,0,1,1,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>HTN_medi<\\/th>\\n      <th>DM_medi<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"HTN_medi\",\"targets\":1},{\"name\":\"DM_medi\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n두 약물 복용 여부를 테이블로 나타내면\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntb.chi <- table(data.chi)\ntb.chi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        DM_medi\nHTN_medi  0  1\n       0 15 13\n       1 14  8\n```\n\n\n:::\n:::\n\n\n이며 언뜻 봐서는 관계가 있는지 아닌지 잘 모르겠다. 이제 `chisq.test`함수를 이용해서 **Chi-square test**를 수행하자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.chi <- chisq.test(tb.chi)\nres.chi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  tb.chi\nX-squared = 0.18246, df = 1, p-value = 0.6693\n```\n\n\n:::\n:::\n\n\n$p$-value는 0.669가 나오고 **혈압약 복용과 당뇨약 복용은 유의한 관계가 없다**고 말할 수 있다.\n\n### 샘플 수 부족: Fisher's exact test\n\n이번엔 다른 사람들의 혈압, 당뇨약 복용 데이터로 **chi-square test**를 수행해 보겠다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5a76a1b853c144c18191\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5a76a1b853c144c18191\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.fisher: HTN &amp; DM medication<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\",\"person 31\",\"person 32\",\"person 33\",\"person 34\",\"person 35\",\"person 36\",\"person 37\",\"person 38\",\"person 39\",\"person 40\",\"person 41\",\"person 42\",\"person 43\",\"person 44\",\"person 45\",\"person 46\",\"person 47\",\"person 48\",\"person 49\",\"person 50\"],[1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1],[0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>HTN_medi<\\/th>\\n      <th>DM_medi<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"HTN_medi\",\"targets\":1},{\"name\":\"DM_medi\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n아까와 마찬가지로 테이블로 두 약물 복용상태를 비교하면 아래와 같다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntb.fisher <- table(data.fisher)\ntb.fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        DM_medi\nHTN_medi  0  1\n       0 31  8\n       1  9  2\n```\n\n\n:::\n:::\n\n\n혈압약과 당뇨약을 모두 복용한 사람이 2명으로 좀 작아보이지만 무시하고 **chi-square test**를 수행하면 결과는 나오나 `Warning` 메시지가 뜬다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(tb.fisher)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(tb.fisher): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  tb.fisher\nX-squared = 4.5971e-31, df = 1, p-value = 1\n```\n\n\n:::\n:::\n\n\n이는 두 약을 모두 복용한 사람이 2명뿐이라서 일어나는 문제로, 일반적으로 분석할 테이블에서 샘플 수가 너무 작은 항이 있으면 **chi-square test**의 계산이 부정확해진다. 이 때는 **fisher's exact test**를 수행하며 아래와 같이 `fisher.test`함수를 이용하면 된다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.fisher <- fisher.test(tb.fisher)\nres.fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  tb.fisher\np-value = 1\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.07627205 5.55561549\nsample estimates:\nodds ratio \n 0.8636115 \n```\n\n\n:::\n:::\n\n\n$p$-value는 1로 확인되고 마찬가지로 혈압약 복용과 당뇨약 복용은 유의한 관계가 없다고 할 수 있다.\n\n여기서 의문점이 들 수 있다. **무조건 fisher's test만 하면 간단한데** 도대체 **chi-square test**는 왜 하는 것일까? 샘플 수가 작을 때는 **fisher's test**만 하는 것이 실제로 더 간단하고 방법론적으로도 아무 문제가 없다. 그러나 샘플 수나 그룹 수가 늘어날수록 **fisher's test**는 필요한 계산량이 급격하게 증가하는 문제가 있어 **chi-square test**를 먼저 수행하는 것을 권유한다.\n\n## 추가: 짝지은 2 그룹\n\n각 사람의 혈압을 한 번은 사람이 직접, 한 번은 자동혈압계로 측정했다고 하자. 이 때 직접 잰 혈압과 자동혈압계의 측정값을 비교한다면 **t-test**로 충분할까? t-test는 혈압 재는 방법마다 **평균을 먼저 구한 후** 그것이 같은지를 테스트하므로 **짝지은 정보를 활용하지 못한다.** 이 때는 각 사람마다 두 혈압값의 **차이를 먼저 구한 후** 평균이 0인지를 테스트하면, 짝지은 정보를 활용하면서 계산도 더 간단한 방법이 된다.\n\n### 연속변수: Paired t-test\n\n위에 언급한 대로 각 사람마다 **차이값을 먼저 구한 후** 그 평균이 0인지를 테스트하는 방법이 **paired t-test**이다. 아래의 수축기 혈압 데이터를 통해 **t-test**와의 차이점을 알아보자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.pt <- data.frame(SBP_hand = round(rnorm(30, mean = 125, sd = 5)), SBP_machine = round(rnorm(30, mean = 125, sd = 5)))\nrownames(data.pt) <- paste(\"person\", 1:30)\ndatatable(data.pt, rownames = T, caption = \"data.pt: systolic blood pressure measured by hand & machine\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-255e85d810d7ec164e0c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-255e85d810d7ec164e0c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.pt: systolic blood pressure measured by hand &amp; machine<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\"],[128,128,120,119,124,130,127,131,127,120,119,131,129,129,125,129,126,132,123,111,125,125,119,112,129,126,125,128,125,128],[128,119,119,126,118,124,128,129,117,130,123,128,128,133,127,126,127,119,122,125,124,127,128,126,127,123,129,123,142,123]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>SBP_hand<\\/th>\\n      <th>SBP_machine<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"SBP_hand\",\"targets\":1},{\"name\":\"SBP_machine\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n위 데이터는 30명의 사람이 앞서 말한 두 가지 방법으로 수축기 혈압을 측정한 데이터이다. 먼저 **t-test**를 수행하자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt.ttest <- t.test(data.pt$SBP_hand, data.pt$SBP_machine)\npt.ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  data.pt$SBP_hand and data.pt$SBP_machine\nt = -0.45768, df = 57.863, p-value = 0.6489\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -3.224307  2.024307\nsample estimates:\nmean of x mean of y \n    125.0     125.6 \n```\n\n\n:::\n:::\n\n\n위 결과를 보면 각 방법의 평균을 먼저 구한 후 그것을 비교한 것을 확인할 수 있고 $p$-value는 0.649이다. 이제 **paired t-test**를 수행하자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt.ttest.pair <- t.test(data.pt$SBP_hand, data.pt$SBP_machine, paired = TRUE)\npt.ttest.pair\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  data.pt$SBP_hand and data.pt$SBP_machine\nt = -0.46171, df = 29, p-value = 0.6477\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -3.257804  2.057804\nsample estimates:\nmean difference \n           -0.6 \n```\n\n\n:::\n:::\n\n\n이번에는 사람마다 차이값을 먼저 구한 후 그것이 0인지 테스트 한 것을 확인할 수 있고 $p$-value는 0.648이다.\n\n**Paired t-test**의 비모수버전은 **wilcoxon-signed rank test** 이며 아래와 같이 실행한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt.wilcox.pair <- wilcox.test(data.pt$SBP_hand, data.pt$SBP_machine, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(data.pt$SBP_hand, data.pt$SBP_machine, paired =\nTRUE): cannot compute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(data.pt$SBP_hand, data.pt$SBP_machine, paired =\nTRUE): cannot compute exact p-value with zeroes\n```\n\n\n:::\n\n```{.r .cell-code}\npt.wilcox.pair\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  data.pt$SBP_hand and data.pt$SBP_machine\nV = 214, p-value = 0.9482\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n본 강의에서는 다루지 않겠지만 짝지은 3개 이상의 그룹은 **repeated measure ANOVA**[^6]라는 방법을 이용한다.\n\n[^6]: https://statistics.laerd.com/statistical-guides/repeated-measures-anova-statistical-guide.php\n\n### 범주형 변수: Mcnemar test, Symmetry test for a paired contingency table\n\n이번에는 측정값이 0,1과 같은 범주형 변수인 경우를 살펴보자. 아래 데이터를 활용해 약 복용 전후로 복통증상 발생에 차이가 있는지 알아본다고 하자.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-d5e5729d1d316c27e452\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d5e5729d1d316c27e452\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>data.mc: Abdominal pain - before &amp; after<\\/caption>\",\"data\":[[\"person 1\",\"person 2\",\"person 3\",\"person 4\",\"person 5\",\"person 6\",\"person 7\",\"person 8\",\"person 9\",\"person 10\",\"person 11\",\"person 12\",\"person 13\",\"person 14\",\"person 15\",\"person 16\",\"person 17\",\"person 18\",\"person 19\",\"person 20\",\"person 21\",\"person 22\",\"person 23\",\"person 24\",\"person 25\",\"person 26\",\"person 27\",\"person 28\",\"person 29\",\"person 30\"],[0,1,0,0,0,1,0,0,0,0,1,1,0,1,0,1,1,0,0,0,1,1,1,0,1,1,0,1,0,1],[0,1,1,0,1,0,0,0,0,1,0,0,0,1,1,0,1,0,1,1,1,0,0,1,0,0,0,1,1,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Pain_before<\\/th>\\n      <th>Pain_after<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Pain_before\",\"targets\":1},{\"name\":\"Pain_after\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n이 데이터를 2 by 2 테이블로 정리하면 아래와 같다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable.mc <- table(data.mc)\ntable.mc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Pain_after\nPain_before 0 1\n          0 8 8\n          1 9 5\n```\n\n\n:::\n:::\n\n\n먼저 앞서 배운 **Chi-sqaure test** 를 이용한 결과를 보자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc.chi <- chisq.test(table.mc)\nmc.chi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table.mc\nX-squared = 0.17514, df = 1, p-value = 0.6756\n```\n\n\n:::\n:::\n\n\n이것은 약 복용 전 복통 증상과 복용 후의 복통 증상이 얼마나 관계가 있는지 알아보는 테스트로 짝지은 정보를 활용하지 않는다. 이번엔 짝지은 정보를 활용하는 **mcnemar test**를 수행하자.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc.mcnemar <- mcnemar.test(table.mc)\nmc.mcnemar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMcNemar's Chi-squared test with continuity correction\n\ndata:  table.mc\nMcNemar's chi-squared = 0, df = 1, p-value = 1\n```\n\n\n:::\n:::\n\n\n**Mcnemar test**는 약 복용후 증상발생이 달라진 사람 즉, **discordant pair**만 분석에 이용한다. 따라서 **condordant pair** 의 구성과 어떻더라도 통계결과는 동일하게 나온다.\n\n한편 측정값이 3개 이상일 때는 **chi-square test**는 그대로 이용할 수 있으나, **mcnemar test**는 그대로 쓰지 못하고 **symmetry test for a paired contingency table**[^7]라는 일반화된 테스트를 사용한다. 본 강의에서는 간단한 실행법만 살펴볼 것이며 먼저 [**rcompanion** R package](http://rcompanion.org/handbook/)를 설치하자.\n\n[^7]: http://rcompanion.org/handbook/H_05.html\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## For symmmetry test\n#install.packages(\"rcompanion\")\nlibrary(rcompanion)\n```\n:::\n\n\n예제 테이블(3 $\\times$ 3)을 아래와 같이 불러온 후\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Example data\ndata(AndersonRainGarden) \nAndersonRainGarden       \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Yes.after No.after Maybe.after\nYes.before           6        0           1\nNo.before            5        3           7\nMaybe.before        11        1          12\n```\n\n\n:::\n:::\n\n\n`nominalSymmetryTest` 함수로 분석을 수행한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Symmetry test\nnominalSymmetryTest(AndersonRainGarden)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Global.test.for.symmetry\n  Dimensions  p.value\n1      3 x 3 0.000476\n\n$Pairwise.symmetry.tests\n                                       Comparison p.value p.adjust\n1       Yes.before/Yes.after : No.before/No.after  0.0736   0.0771\n2 Yes.before/Yes.after : Maybe.before/Maybe.after 0.00937   0.0281\n3   No.before/No.after : Maybe.before/Maybe.after  0.0771   0.0771\n\n$p.adjustment\n  Method\n1    fdr\n\n$statistical.method\n        Method\n1 McNemar test\n```\n\n\n:::\n:::\n\n\n## 실습\n\n### [웹 애플리케이션](https://jinseob2kim.shinyapps.io/BasicStat/)\n\n[**Anpanman**](https://www.anpanman.co.kr/) 에서 만든 [기초통계 앱](https://jinseob2kim.shinyapps.io/BasicStat/)을 소개한다(Figure \\@ref(fig:appgif)). 5메가 이하의 **excel**, **csv** 형태 혹은 **sas**, **spss** 프로그램으로 만든 데이터를 업로드하면 Table 1과 회귀분석, 로지스틱 회귀분석을 간단하게 수행하고 결과를 **excel**로 바로 다운받을 수 있다.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Application mady by Anpanman](app.gif)\n:::\n:::\n\n\n### [Rstudio Addins](https://rstudio.github.io/rstudioaddins/)\n\n5메가보다 큰 데이터는 [**R**](https://www.r-project.org/)에서 데이터를 읽은 후, 자체적으로 만든 [**jsmodule** R package](https://github.com/jinseob2kim/jsmodule)를 설치하여 앱을 이용할 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## For private package install \ninstall.packages(\"devtools\")   \ndevtools::install_github(c(\"jinseob2kim/jstable\", \"jinseob2kim/jsmodule\")) \n```\n:::\n\n\n패키지를 설치한 후 [**Rstudio**](https://www.rstudio.com/) 프로그램의 **Addins** 탭을 누르면 **Basic statistics** 항목이 보일 것이다. 데이터를 읽고 그것의 이름을 드래그 한 상태로 **Basic statistics** 를 누르면 된다(Figure \\@ref(fig:addingif)).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Rstudo Addins made by Anpanman^[https://github.com/jinseob2kim/jsmodule]](addin.gif)\n:::\n:::\n\n\n직접 [**R**](https://www.r-project.org/)에서 코드를 실행하고 싶은 유저는 [**tableone** R package](https://github.com/kaz-yos/tableone)를 참고하기 바란다.\n\n## 마치며\n\n지금까지 의학 연구에서 쓰이는 그룹 비교 통계들을 알아보고 [웹 앱](https://jinseob2kim.shinyapps.io/BasicStat/)과 [**Rstudio Addins**](https://rstudio.github.io/rstudioaddins/) 을 이용하여 직접 Table 1을 만들어보았다. 앞으로 연구자들은 어려운 통계 프로그램을 이용할 필요 없이 [**Anpanman**](https://www.anpanman.co.kr/)의 서비스를 활용, 빠르게 통계 분석을 수행하고 테이블과 그림을 바로 다운받을 수 있다.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}