on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Require Netlify token (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          if [ -z "${NETLIFY_AUTH_TOKEN}" ]; then
            echo "::error::Missing NETLIFY_DEV_AUTH_TOKEN secret for dev deploy"
            exit 1
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH_TOKEN }}

      - name: Require Netlify token (prod)
        if: github.ref == 'refs/heads/master'
        run: |
          if [ -z "${NETLIFY_AUTH_TOKEN}" ]; then
            echo "::error::Missing NETLIFY_PROD_AUTH_TOKEN secret for prod deploy"
            exit 1
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PROD_AUTH_TOKEN }}

      - name: Install system libraries
        run: |
          set -xe
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libarchive-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"
          use-public-rspm: true

      - name: Install R dependencies
        run: Rscript _install_packages.R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Run genjson.py
        run: python genjson.py

      - name: Copy posts.json to _site
        run: mkdir -p _site && cp posts.json _site/posts.json

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto (ko)
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: ko

      - name: Render Quarto (en)
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en

      - name: Render Quarto (jp)
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: jp

      - name: Publish to Netlify (dev)
        if: github.ref == 'refs/heads/dev'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          render: "false"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH_TOKEN }}
        env:
          QUARTO_PROFILE: dev
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH_TOKEN }}

      - name: Publish to Netlify (prod)
        if: github.ref == 'refs/heads/master'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          render: "false"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PROD_AUTH_TOKEN }}
        env:
          QUARTO_PROFILE: prod
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PROD_AUTH_TOKEN }}
